repos:
- repo: local
  hooks:
  - id: ruff-check
    name: ruff check
    entry: uvx ruff check
    language: system
    types: [python]
  - id: ruff-format
    name: ruff format
    entry: uvx ruff format --check
    language: system
    types: [python]
  - id: pyright
    name: pyright
    entry: uv run pyright voice_assistant
    language: system
    types: [python]
    pass_filenames: false
  - id: nixfmt
    name: nixfmt
    entry: nix run nixpkgs#nixfmt
    language: system
    files: flake\.nix
